Traceback (most recent call last):
  File "C:\Users\mhelsaye\Anaconda3\envs\TEP4222\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\mhelsaye\Anaconda3\envs\TEP4222\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\mhelsaye\Anaconda3\envs\TEP4222\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\mhelsaye\Anaconda3\envs\TEP4222\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\mhelsaye\Anaconda3\envs\TEP4222\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\mhelsaye\Anaconda3\envs\TEP4222\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mhelsaye\Anaconda3\envs\TEP4222\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\mhelsaye\Anaconda3\envs\TEP4222\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df = pd.read_excel('NO_2010.xlsx',usecols='A:J', index_col=0)
df
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_20996/2821394461.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mdf[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_excel[0m[1;33m([0m[1;34m'NO_2010.xlsx'[0m[1;33m,[0m[0musecols[0m[1;33m=[0m[1;34m'A:J'[0m[1;33m,[0m [0mindex_col[0m[1;33m=[0m[1;36m0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mdf[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\TEP4222\lib\site-packages\pandas\util\_decorators.py[0m in [0;36mwrapper[1;34m(*args, **kwargs)[0m
[0;32m    309[0m                     [0mstacklevel[0m[1;33m=[0m[0mstacklevel[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    310[0m                 )
[1;32m--> 311[1;33m             [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    312[0m [1;33m[0m[0m
[0;32m    313[0m         [1;32mreturn[0m [0mwrapper[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\TEP4222\lib\site-packages\pandas\io\excel\_base.py[0m in [0;36mread_excel[1;34m(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, thousands, decimal, comment, skipfooter, convert_float, mangle_dupe_cols, storage_options)[0m
[0;32m    455[0m     [1;32mif[0m [1;32mnot[0m [0misinstance[0m[1;33m([0m[0mio[0m[1;33m,[0m [0mExcelFile[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    456[0m         [0mshould_close[0m [1;33m=[0m [1;32mTrue[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 457[1;33m         [0mio[0m [1;33m=[0m [0mExcelFile[0m[1;33m([0m[0mio[0m[1;33m,[0m [0mstorage_options[0m[1;33m=[0m[0mstorage_options[0m[1;33m,[0m [0mengine[0m[1;33m=[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    458[0m     [1;32melif[0m [0mengine[0m [1;32mand[0m [0mengine[0m [1;33m!=[0m [0mio[0m[1;33m.[0m[0mengine[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    459[0m         raise ValueError(

[1;32m~\Anaconda3\envs\TEP4222\lib\site-packages\pandas\io\excel\_base.py[0m in [0;36m__init__[1;34m(self, path_or_buffer, engine, storage_options)[0m
[0;32m   1374[0m                 [0mext[0m [1;33m=[0m [1;34m"xls"[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1375[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1376[1;33m                 ext = inspect_excel_format(
[0m[0;32m   1377[0m                     [0mcontent_or_path[0m[1;33m=[0m[0mpath_or_buffer[0m[1;33m,[0m [0mstorage_options[0m[1;33m=[0m[0mstorage_options[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1378[0m                 )

[1;32m~\Anaconda3\envs\TEP4222\lib\site-packages\pandas\io\excel\_base.py[0m in [0;36minspect_excel_format[1;34m(content_or_path, storage_options)[0m
[0;32m   1248[0m         [0mcontent_or_path[0m [1;33m=[0m [0mBytesIO[0m[1;33m([0m[0mcontent_or_path[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1249[0m [1;33m[0m[0m
[1;32m-> 1250[1;33m     with get_handle(
[0m[0;32m   1251[0m         [0mcontent_or_path[0m[1;33m,[0m [1;34m"rb"[0m[1;33m,[0m [0mstorage_options[0m[1;33m=[0m[0mstorage_options[0m[1;33m,[0m [0mis_text[0m[1;33m=[0m[1;32mFalse[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1252[0m     ) as handle:

[1;32m~\Anaconda3\envs\TEP4222\lib\site-packages\pandas\io\common.py[0m in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    793[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    794[0m             [1;31m# Binary mode[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 795[1;33m             [0mhandle[0m [1;33m=[0m [0mopen[0m[1;33m([0m[0mhandle[0m[1;33m,[0m [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    796[0m         [0mhandles[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mhandle[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    797[0m [1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'NO_2010.xlsx'
FileNotFoundError: [Errno 2] No such file or directory: 'NO_2010.xlsx'

